import {Reservation} from '@/model/reservation'
import * as db from '@/services/aws/db'
import Msg from '@/services/msg'

const reservationConverter = function (reservation) {
    return new Reservation(
        reservation.id,
        reservation.applyDate,
        reservation.reservationDate,
        reservation.dueDate,
        reservation.verifyDate,
        reservation.takeDate,
        reservation.returnDate,
        reservation.status,
        reservation.userID,
        reservation.bookID,
    )
}

const reservationService = {
    createReservation(reservation) {
        return new Promise((resolve, reject) => {
            // Step1 get the autogenerated ID after createBook action
            db.mutations(reservationConverter(reservation), 'createReservation')
                .then(resolve)
                .catch(reject)
        })
    },

    updateReservation(reservation) {
        return new Promise((resolve, reject) => {
            db.mutations(reservationConverter(reservation), 'updateReservation')
                .then(resolve)
                .catch(reject)
        })
    },

    deleteReservation(id) {
        return new Promise((resolve, reject) => {
            db.mutations({id}, 'deleteReservation')
                .then(resolve)
                .catch(reject)
        })
    },

    getReservations(filter) {
        return new Promise((resolve, reject) => {
            db.queries('listReservations', filter ? {filter} : null)
                .then(data => {
                    resolve(data.items)
                })
                .catch(reject)
        })
    },

    getAll() {
        return this.getReservations();
    },

    getAllByUserID(userID) {
        return this.getReservations({
            userID: {
                eq: userID
            }
        })
    },

    subscribe(onCreateFn, onUpdateFn, onDeleteFn) {
        if (typeof onCreateFn === 'function')
            db.subscriptions('onCreateReservation', (eventData) => onCreateFn(eventData.value.data.onCreateReservation))
        if (typeof onUpdateFn === 'function')
            db.subscriptions('onUpdateReservation', (eventData) => onUpdateFn(eventData.value.data.onUpdateReservation))
        if (typeof onDeleteFn === 'function')
            db.subscriptions('onDeleteReservation', (eventData) => onDeleteFn(eventData.value.data.onDeleteReservation))
    },

    cancelReservation(reservation) {
        reservation.status = 'C'

        this.updateReservation(reservation)
            .then(() => Msg.success(Msg.i18N.success_reservation_cancel))
            .catch(err => Msg.error(Msg.i18N.err_reservation_cancel, err))
    }
}

export default reservationService